In [2]:
import numpy as np

In [3]:
n1 = np.array([1,2,3,4])
n1

array([1, 2, 3, 4])

In [4]:
type(n1)

numpy.ndarray

In [5]:
n2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])
n2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [6]:
type(n2)

numpy.ndarray

In [8]:
#zeros method
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
n4 = np.zeros((6,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
#full method
n5 = np.full((3,3),(5))
n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
#arange method
n6 = np.arange(10,51)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
n7 = np.arange(1,105,10)
n7

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [14]:
#random method
n8 = np.random.randint(100,1000,10)
n8

array([918, 150, 348, 311, 817, 841, 848, 158, 147, 970])

In [15]:
#shape method
n9 = np.array([[1,2,3],[4,5,6]])
n9

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
n9.shape

(2, 3)

In [18]:
n9.shape = (3,2)
n9

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
#stacking operations
n10 = np.array([10,20,30])
n11 = np.array([100,200,300])

In [4]:
np.vstack((n10,n11))

array([[ 10,  20,  30],
       [100, 200, 300]])

In [5]:
np.hstack((n10,n11))

array([ 10,  20,  30, 100, 200, 300])

In [6]:
np.column_stack((n10,n11))

array([[ 10, 100],
       [ 20, 200],
       [ 30, 300]])

In [8]:
#intersection method
n12 = np.array([10,20,30,40,50,60])
n13 = np.array([50,60,70,80,90])

In [11]:
np.intersect1d(n12,n13)

array([50, 60])

In [12]:
np.setdiff1d(n12,n13)

array([10, 20, 30, 40])

In [13]:
np.setdiff1d(n13,n12)

array([70, 80, 90])

In [3]:
#addition of numpy arrays
n14 = np.array([10,20])
n15 = np.array([30,40])

In [4]:
np.sum([n14,n15])

100

In [5]:
np.sum([n14,n15],axis=0)

array([40, 60])

In [6]:
np.sum([n14,n15],axis=1)

array([30, 70])

In [7]:
n16 = np.array([10,20,30])

In [8]:
n16 + 1

array([11, 21, 31])

In [9]:
n16 - 1

array([ 9, 19, 29])

In [10]:
n16 * 10

array([100, 200, 300])

In [11]:
n16 / 2

array([ 5., 10., 15.])

In [12]:
np.mean(n16)

20.0

In [13]:
np.median(n16)

20.0

In [14]:
np.std(n16)

8.16496580927726

In [15]:
n17 = np.array([10,20,30,40,50,60])

In [16]:
np.save('my_array',n17)

In [17]:
n18 = np.load('my_array.npy')

In [18]:
n18

array([10, 20, 30, 40, 50, 60])